-- =============================================================================
-- SD Presales Dashboard: Cache Table Infrastructure
-- Run this script once in Snowsight to set up materialized cache tables,
-- the refresh stored procedure, and the twice-daily scheduled Task.
-- After running, the tables will be auto-populated.
-- =============================================================================

USE ROLE TECHNICAL_ACCOUNT_MANAGER;
USE WAREHOUSE PST_STEAMLIT_APPS;
USE DATABASE SD_APPS_DB;
USE SCHEMA SD_CENTER;

-- ---------------------------------------------------------------------------
-- 1. Metadata table: tracks last refresh time per cache table
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS SD_APPS_DB.SD_CENTER.SD_CACHE_METADATA (
    TABLE_NAME        VARCHAR        NOT NULL,
    LAST_REFRESHED_AT TIMESTAMP_LTZ,
    ROW_COUNT         INT,
    PRIMARY KEY (TABLE_NAME)
);

-- ---------------------------------------------------------------------------
-- 2. Stored procedure: refreshes all 15 cache tables atomically
--    EXECUTE AS CALLER so RAVEN row-access policies resolve correctly
-- ---------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SD_APPS_DB.SD_CENTER.REFRESH_CACHE_ALL()
  RETURNS VARCHAR
  LANGUAGE SQL
  EXECUTE AS CALLER
AS
$$
BEGIN

  -- ── 1. SD_CACHE_ACCOUNTS_BASE ─────────────────────────────────────────────
  CREATE OR REPLACE TABLE SD_APPS_DB.SD_CENTER.SD_CACHE_ACCOUNTS_BASE AS
  SELECT
      a.ACCOUNT_NAME,
      a.ACCOUNT_ID AS SALESFORCE_ACCOUNT_ID,
      a.REP_NAME AS ACCOUNT_OWNER,
      COALESCE(_dm.NAME, a.DM) AS DM,
      a.RVP,
      CAST(a.ARR AS FLOAT) AS ARR,
      CAST(a.APS AS FLOAT) AS APS,
      a.INDUSTRY,
      a.SUB_INDUSTRY AS SUBINDUSTRY,
      a.ACCOUNT_TIER AS TIER,
      a.SEGMENT,
      a.BILLING_CITY,
      a.BILLING_STATE,
      a.BILLING_COUNTRY,
      a.NUMBER_OF_EMPLOYEES,
      a.LAST_ACTIVITY_DATE,
      lead_se.NAME AS LEAD_SE,
      a.MATURITY_SCORE_C,
      a.CONSUMPTION_RISK_C,
      a.ACCOUNT_STRATEGY_C,
      a.ACCOUNT_RISK_C,
      a.ACCOUNT_COMMENTS_C,
      a.CONSUMPTION_RISK_MITIGATION_STEPS_C,
      CAST(a.PREDICTED_1_YV_C AS FLOAT) AS PREDICTED_1YV,
      CAST(a.PREDICTED_3_YV_C AS FLOAT) AS PREDICTED_3YV,
      a.TOTAL_ACCOUNTS,
      a.AWS_ACCOUNTS,
      a.AZURE_ACCOUNTS,
      a.GCP_ACCOUNTS,
      a.DISTRICT_NAME
  FROM SNOWHOUSE.SALES.ACCOUNTS_DAILY a
  JOIN FIVETRAN.SALESFORCE.ACCOUNT fa ON a.ACCOUNT_ID = fa.ID
  LEFT JOIN FIVETRAN.SALESFORCE.USER lead_se ON fa.LEAD_SALES_ENGINEER_C = lead_se.ID
  LEFT JOIN (SELECT NAME, MANAGER_ID FROM FIVETRAN.SALESFORCE.USER WHERE IS_ACTIVE = true QUALIFY ROW_NUMBER() OVER (PARTITION BY NAME ORDER BY ID) = 1) _ae ON a.REP_NAME = _ae.NAME
  LEFT JOIN FIVETRAN.SALESFORCE.USER _dm ON _ae.MANAGER_ID = _dm.ID
  WHERE a.ACCOUNT_STATUS = 'Active'
  AND a.DS = (SELECT MAX(DS) FROM SNOWHOUSE.SALES.ACCOUNTS_DAILY)
  ORDER BY a.ARR DESC;

  MERGE INTO SD_APPS_DB.SD_CENTER.SD_CACHE_METADATA t
  USING (SELECT 'SD_CACHE_ACCOUNTS_BASE' AS TABLE_NAME, CURRENT_TIMESTAMP() AS TS,
         (SELECT COUNT(*) FROM SD_APPS_DB.SD_CENTER.SD_CACHE_ACCOUNTS_BASE) AS CNT) s
  ON t.TABLE_NAME = s.TABLE_NAME
  WHEN MATCHED THEN UPDATE SET LAST_REFRESHED_AT = s.TS, ROW_COUNT = s.CNT
  WHEN NOT MATCHED THEN INSERT (TABLE_NAME, LAST_REFRESHED_AT, ROW_COUNT) VALUES (s.TABLE_NAME, s.TS, s.CNT);

  -- ── 2. SD_CACHE_CAPACITY_RENEWALS ─────────────────────────────────────────
  CREATE OR REPLACE TABLE SD_APPS_DB.SD_CENTER.SD_CACHE_CAPACITY_RENEWALS AS
  WITH base AS (
      SELECT
          a.ACCOUNT_ID AS SALESFORCE_ACCOUNT_ID,
          a.ACCOUNT_NAME,
          a.REP_NAME AS ACCOUNT_OWNER,
          COALESCE(dm_user.NAME, a.DM) AS DM,
          a.ACCOUNT_TIER AS TIER,
          a.DISTRICT_NAME
      FROM SNOWHOUSE.SALES.ACCOUNTS_DAILY a
      LEFT JOIN (SELECT NAME, MANAGER_ID FROM FIVETRAN.SALESFORCE.USER WHERE IS_ACTIVE = true QUALIFY ROW_NUMBER() OVER (PARTITION BY NAME ORDER BY ID) = 1) ae_user ON a.REP_NAME = ae_user.NAME
      LEFT JOIN FIVETRAN.SALESFORCE.USER dm_user ON ae_user.MANAGER_ID = dm_user.ID
      WHERE a.DS = (SELECT MAX(DS) FROM SNOWHOUSE.SALES.ACCOUNTS_DAILY)
      AND a.ACCOUNT_STATUS = 'Active'
  ),
  capacity AS (
      SELECT
          dc.SALESFORCE_ACCOUNT_ID,
          MAX(dc.CONTRACT_START_DATE) AS CONTRACT_START_DATE,
          MAX(dc.CONTRACT_END_DATE) AS CONTRACT_END_DATE,
          CAST(SUM(dc.CAPACITY_PURCHASED) AS FLOAT) AS CAP_PURCHASED,
          CAST(SUM(dc.TOTAL_CAPACITY) AS FLOAT) AS TOTAL_CAP,
          CAST(SUM(dc.TOTAL_CAPACITY - dc.CAPACITY_USAGE_REMAINING) AS FLOAT) AS CAP_USED,
          CAST(SUM(dc.CAPACITY_USAGE_REMAINING) AS FLOAT) AS CAP_REMAINING
      FROM SALES.RAVEN.DIM_CONTRACT_VIEW dc
      WHERE dc.AGREEMENT_TYPE = 'Capacity'
      AND dc.CAPACITY_PURCHASED > 0
      AND dc.CONTRACT_END_DATE = (
          SELECT MAX(dc2.CONTRACT_END_DATE)
          FROM SALES.RAVEN.DIM_CONTRACT_VIEW dc2
          WHERE dc2.SALESFORCE_ACCOUNT_ID = dc.SALESFORCE_ACCOUNT_ID
          AND dc2.AGREEMENT_TYPE = 'Capacity' AND dc2.CAPACITY_PURCHASED > 0
      )
      GROUP BY dc.SALESFORCE_ACCOUNT_ID
  ),
  capacity_fallback AS (
      SELECT
          f.SALESFORCE_ACCOUNT_ID,
          f.SEGMENT_CONTRACT_START_DATE AS CONTRACT_START_DATE,
          f.SEGMENT_CONTRACT_END_DATE AS CONTRACT_END_DATE,
          CAST(NULL AS FLOAT) AS CAP_PURCHASED,
          CAST(NULL AS FLOAT) AS TOTAL_CAP,
          CAST(NULL AS FLOAT) AS CAP_USED,
          CAST(f.SEGMENT_CONTRACT_CAPACITY_REMAINING_ AS FLOAT) AS CAP_REMAINING
      FROM SNOWHOUSE.SALES.FUTURE_CONTRACT_SEGMENT_OVERAGE f
      WHERE f._DATE = f.DS
      QUALIFY ROW_NUMBER() OVER (PARTITION BY f.SALESFORCE_ACCOUNT_ID ORDER BY f.SEGMENT_CONTRACT_END_DATE DESC) = 1
  ),
  overage AS (
      SELECT
          ov.SALESFORCE_ACCOUNT_ID,
          CAST(SUM(ov.OVERAGE_UNDERAGE_PREDICTION) AS FLOAT) AS OVERAGE_UNDERAGE_PREDICTION,
          MAX(ov.DAY_OF_OVERAGE) AS OVERAGE_DATE
      FROM SALES.RAVEN.A360_OVERAGE_UNDERAGE_PREDICTION_VIEW ov
      WHERE ov.CONTRACT_END_DATE = (
          SELECT MAX(ov2.CONTRACT_END_DATE)
          FROM SALES.RAVEN.A360_OVERAGE_UNDERAGE_PREDICTION_VIEW ov2
          WHERE ov2.SALESFORCE_ACCOUNT_ID = ov.SALESFORCE_ACCOUNT_ID
      )
      GROUP BY ov.SALESFORCE_ACCOUNT_ID
  ),
  overage_fallback AS (
      SELECT
          f.SALESFORCE_ACCOUNT_ID,
          CAST(f.SEGMENT_CONTRACT_CAPACITY_REMAINING_ AS FLOAT) AS OVERAGE_UNDERAGE_PREDICTION,
          f.OVERAGE_DATE
      FROM SNOWHOUSE.SALES.FUTURE_CONTRACT_SEGMENT_OVERAGE f
      WHERE f._DATE = f.DS
      QUALIFY ROW_NUMBER() OVER (PARTITION BY f.SALESFORCE_ACCOUNT_ID ORDER BY f.SEGMENT_CONTRACT_END_DATE DESC) = 1
  ),
  lead_se AS (
      SELECT fa.ID AS SALESFORCE_ACCOUNT_ID, u.NAME AS LEAD_SE
      FROM FIVETRAN.SALESFORCE.ACCOUNT fa
      LEFT JOIN FIVETRAN.SALESFORCE.USER u ON fa.LEAD_SALES_ENGINEER_C = u.ID
  )
  SELECT
      b.ACCOUNT_NAME,
      b.SALESFORCE_ACCOUNT_ID,
      b.ACCOUNT_OWNER,
      b.DM,
      b.DISTRICT_NAME,
      b.TIER,
      ls.LEAD_SE,
      IFF(YEAR(COALESCE(cap.CONTRACT_START_DATE, fb.CONTRACT_START_DATE)) BETWEEN 1900 AND 2200, COALESCE(cap.CONTRACT_START_DATE, fb.CONTRACT_START_DATE), NULL) AS CONTRACT_START_DATE,
      IFF(YEAR(COALESCE(cap.CONTRACT_END_DATE,   fb.CONTRACT_END_DATE))   BETWEEN 1900 AND 2200, COALESCE(cap.CONTRACT_END_DATE,   fb.CONTRACT_END_DATE),   NULL) AS CONTRACT_END_DATE,
      COALESCE(cap.CAP_PURCHASED, fb.CAP_PURCHASED) AS CAP_PURCHASED,
      COALESCE(cap.TOTAL_CAP,     fb.TOTAL_CAP)     AS TOTAL_CAP,
      COALESCE(cap.CAP_USED,      fb.CAP_USED)      AS CAP_USED,
      COALESCE(cap.CAP_REMAINING, fb.CAP_REMAINING) AS CAP_REMAINING,
      COALESCE(ovp.OVERAGE_UNDERAGE_PREDICTION, ovf.OVERAGE_UNDERAGE_PREDICTION) AS OVERAGE_UNDERAGE_PREDICTION,
      IFF(YEAR(COALESCE(ovp.OVERAGE_DATE, ovf.OVERAGE_DATE)) BETWEEN 1900 AND 2200, COALESCE(ovp.OVERAGE_DATE, ovf.OVERAGE_DATE), NULL) AS OVERAGE_DATE
  FROM base b
  LEFT JOIN capacity          cap ON b.SALESFORCE_ACCOUNT_ID = cap.SALESFORCE_ACCOUNT_ID
  LEFT JOIN capacity_fallback fb  ON b.SALESFORCE_ACCOUNT_ID = fb.SALESFORCE_ACCOUNT_ID
  LEFT JOIN overage           ovp ON b.SALESFORCE_ACCOUNT_ID = ovp.SALESFORCE_ACCOUNT_ID
  LEFT JOIN overage_fallback  ovf ON b.SALESFORCE_ACCOUNT_ID = ovf.SALESFORCE_ACCOUNT_ID
  LEFT JOIN lead_se           ls  ON b.SALESFORCE_ACCOUNT_ID = ls.SALESFORCE_ACCOUNT_ID
  WHERE COALESCE(cap.CONTRACT_END_DATE, fb.CONTRACT_END_DATE) IS NOT NULL
  ORDER BY COALESCE(cap.CAP_PURCHASED, fb.CAP_PURCHASED) DESC NULLS LAST;

  MERGE INTO SD_APPS_DB.SD_CENTER.SD_CACHE_METADATA t
  USING (SELECT 'SD_CACHE_CAPACITY_RENEWALS' AS TABLE_NAME, CURRENT_TIMESTAMP() AS TS,
         (SELECT COUNT(*) FROM SD_APPS_DB.SD_CENTER.SD_CACHE_CAPACITY_RENEWALS) AS CNT) s
  ON t.TABLE_NAME = s.TABLE_NAME
  WHEN MATCHED THEN UPDATE SET LAST_REFRESHED_AT = s.TS, ROW_COUNT = s.CNT
  WHEN NOT MATCHED THEN INSERT (TABLE_NAME, LAST_REFRESHED_AT, ROW_COUNT) VALUES (s.TABLE_NAME, s.TS, s.CNT);

  -- ── 3. SD_CACHE_CAPACITY_PIPELINE ─────────────────────────────────────────
  CREATE OR REPLACE TABLE SD_APPS_DB.SD_CENTER.SD_CACHE_CAPACITY_PIPELINE AS
  SELECT
      o.ACCOUNT_NAME,
      o.ACCOUNT_ID AS SALESFORCE_ACCOUNT_ID,
      o.OPP_NAME AS OPPORTUNITY_NAME,
      o.OPP_ID AS OPPORTUNITY_ID,
      o.TYPE AS OPPORTUNITY_TYPE,
      o.AGREEMENT_TYPE AS AGREEMENT_TYPE,
      o.STAGE_NAME,
      o.FORECAST_STATUS,
      CAST(COALESCE(sf.FORECAST_ACV_C, 0) AS FLOAT) AS PRODUCT_FORECAST_ACV,
      CAST(COALESCE(sf.PRODUCT_FORECAST_TCV_C, 0) AS FLOAT) AS PRODUCT_FORECAST_TCV,
      CAST(
          CASE WHEN COALESCE(sf.PRODUCT_FORECAST_TCV_C, 0) > 0
               THEN sf.PRODUCT_FORECAST_TCV_C
               ELSE COALESCE(sf.FORECAST_ACV_C, 0)
          END AS FLOAT
      ) AS CALCULATED_TCV,
      o.CLOSE_DATE,
      fc.FISCAL_PERIOD AS FISCAL_QUARTER,
      o.REP_NAME AS OWNER,
      o.SE_COMMENTS_C AS SE_COMMENTS,
      o.NEXT_STEPS,
      COALESCE(_dm.NAME, o.DM) AS DM,
      o.DISTRICT_NAME
  FROM SNOWHOUSE.SALES.OPPORTUNITIES_DAILY o
  LEFT JOIN SNOWHOUSE.UTILS.FISCAL_CALENDAR fc ON fc._DATE = o.CLOSE_DATE
  LEFT JOIN FIVETRAN.SALESFORCE.OPPORTUNITY sf ON sf.ID = o.OPP_ID
  LEFT JOIN (SELECT NAME, MANAGER_ID FROM FIVETRAN.SALESFORCE.USER WHERE IS_ACTIVE = true QUALIFY ROW_NUMBER() OVER (PARTITION BY NAME ORDER BY ID) = 1) _ae ON o.REP_NAME = _ae.NAME
  LEFT JOIN FIVETRAN.SALESFORCE.USER _dm ON _ae.MANAGER_ID = _dm.ID
  WHERE o.DS = (SELECT MAX(DS) FROM SNOWHOUSE.SALES.OPPORTUNITIES_DAILY)
  AND o.IS_CLOSED = FALSE
  AND o.CLOSE_DATE >= CURRENT_DATE()
  QUALIFY ROW_NUMBER() OVER (PARTITION BY o.ACCOUNT_ID, o.OPP_NAME ORDER BY o.OPP_ID DESC) = 1
  ORDER BY o.CLOSE_DATE ASC;

  MERGE INTO SD_APPS_DB.SD_CENTER.SD_CACHE_METADATA t
  USING (SELECT 'SD_CACHE_CAPACITY_PIPELINE' AS TABLE_NAME, CURRENT_TIMESTAMP() AS TS,
         (SELECT COUNT(*) FROM SD_APPS_DB.SD_CENTER.SD_CACHE_CAPACITY_PIPELINE) AS CNT) s
  ON t.TABLE_NAME = s.TABLE_NAME
  WHEN MATCHED THEN UPDATE SET LAST_REFRESHED_AT = s.TS, ROW_COUNT = s.CNT
  WHEN NOT MATCHED THEN INSERT (TABLE_NAME, LAST_REFRESHED_AT, ROW_COUNT) VALUES (s.TABLE_NAME, s.TS, s.CNT);

  -- ── 4. SD_CACHE_USE_CASES ─────────────────────────────────────────────────
  CREATE OR REPLACE TABLE SD_APPS_DB.SD_CENTER.SD_CACHE_USE_CASES AS
  SELECT
      a.ACCOUNT_NAME,
      a.ACCOUNT_ID AS SALESFORCE_ACCOUNT_ID,
      uc.NAME_C AS USE_CASE_NAME,
      uc.USE_CASE_STATUS_C AS USE_CASE_STATUS,
      CAST(uc.ESTIMATED_ANNUAL_CREDIT_CONSUMPTION_C AS FLOAT) AS ACV,
      uc.STAGE_C AS STAGE,
      uc.TECHNICAL_WIN_C AS TECHNICAL_WIN,
      uc.ACTUAL_GO_LIVE_DATE_C AS ACTUAL_GO_LIVE,
      uc.CREATED_DATE,
      uc.LAST_MODIFIED_DATE,
      uc.LAST_STAGE_CHANGE_IN_DAYS_C AS DAYS_IN_STAGE,
      u.NAME AS OWNER,
      uc.NEXT_STEPS_C AS NEXT_STEPS,
      (uc.PS_ENGAGEMENT_C IS NOT NULL AND uc.PS_ENGAGEMENT_C != 'Not Yet Known') AS IS_PS_ENGAGED,
      uc.PS_ENGAGEMENT_C AS PS_ENGAGEMENT,
      NULL AS PS_DESCRIPTION,
      COALESCE(_dm.NAME, a.DM) AS DM,
      a.DISTRICT_NAME,
      a.SUB_INDUSTRY AS ACCOUNT_SUB_INDUSTRY,
      uc.COMPETITORS_C AS COMPETITORS,
      uc.MISSION_CRITICAL_C AS MISSION_CRITICAL,
      uc.TECHNICAL_USE_CASE_C AS TECHNICAL_USE_CASE,
      uc.ID AS USE_CASE_ID,
      uc.NAME AS USE_CASE_NUMBER,
      uc.DECISION_DATE_C AS DECISION_DATE,
      uc.IMPLEMENTER_C AS IMPLEMENTER,
      uc.TECHNICAL_WIN_DATE_FORECAST_C AS TARGET_GO_LIVE,
      uc.USE_CASE_COMMENTS_C AS KEY_NOTES
  FROM FIVETRAN.SALESFORCE.USE_CASE_C uc
  JOIN SNOWHOUSE.SALES.ACCOUNTS_DAILY a ON uc.ACCOUNT_C = a.ACCOUNT_ID AND a.DS = (SELECT MAX(DS) FROM SNOWHOUSE.SALES.ACCOUNTS_DAILY)
  LEFT JOIN (SELECT NAME, MANAGER_ID FROM FIVETRAN.SALESFORCE.USER WHERE IS_ACTIVE = true QUALIFY ROW_NUMBER() OVER (PARTITION BY NAME ORDER BY ID) = 1) _ae ON a.REP_NAME = _ae.NAME
  LEFT JOIN FIVETRAN.SALESFORCE.USER _dm ON _ae.MANAGER_ID = _dm.ID
  LEFT JOIN FIVETRAN.SALESFORCE.USER u ON uc.OWNER_ID = u.ID
  WHERE uc.STAGE_C IS NOT NULL
  AND uc.STAGE_C != '8 - Use Case Lost'
  AND uc._FIVETRAN_DELETED = FALSE
  ORDER BY uc.LAST_STAGE_CHANGE_IN_DAYS_C DESC NULLS LAST;

  MERGE INTO SD_APPS_DB.SD_CENTER.SD_CACHE_METADATA t
  USING (SELECT 'SD_CACHE_USE_CASES' AS TABLE_NAME, CURRENT_TIMESTAMP() AS TS,
         (SELECT COUNT(*) FROM SD_APPS_DB.SD_CENTER.SD_CACHE_USE_CASES) AS CNT) s
  ON t.TABLE_NAME = s.TABLE_NAME
  WHEN MATCHED THEN UPDATE SET LAST_REFRESHED_AT = s.TS, ROW_COUNT = s.CNT
  WHEN NOT MATCHED THEN INSERT (TABLE_NAME, LAST_REFRESHED_AT, ROW_COUNT) VALUES (s.TABLE_NAME, s.TS, s.CNT);

  -- ── 5. SD_CACHE_PS_PROJECTS_ACTIVE ────────────────────────────────────────
  CREATE OR REPLACE TABLE SD_APPS_DB.SD_CENTER.SD_CACHE_PS_PROJECTS_ACTIVE AS
  WITH assignments AS (
      SELECT
          asgn.PSE_PROJECT_C AS PROJECT_ID,
          COUNT(asgn.ID) AS ASSIGNMENT_COUNT,
          LISTAGG(DISTINCT r.NAME, ', ') WITHIN GROUP (ORDER BY r.NAME) AS RESOURCES,
          LISTAGG(DISTINCT asgn.PSE_ROLE_C, ', ') WITHIN GROUP (ORDER BY asgn.PSE_ROLE_C) AS ROLES,
          MAX(asgn.PSE_END_DATE_C) AS LAST_RESOURCE_END_DATE
      FROM FIVETRAN.SALESFORCE.PSE_ASSIGNMENT_C asgn
      LEFT JOIN FIVETRAN.SALESFORCE.CONTACT r ON asgn.PSE_RESOURCE_C = r.ID
      WHERE asgn.IS_DELETED = FALSE
      GROUP BY asgn.PSE_PROJECT_C
  )
  SELECT
      p.NAME AS PROJECT_NAME,
      p.ID AS PROJECT_ID,
      a.ACCOUNT_NAME AS ACCOUNT_NAME,
      a.ACCOUNT_ID AS SALESFORCE_ACCOUNT_ID,
      p.PSE_PROJECT_STATUS_C AS PROJECT_STATUS,
      p.PSE_STAGE_C AS PROJECT_STAGE,
      pr.NAME AS PRACTICE,
      p.SERVICE_TYPE_C AS SERVICE_TYPE,
      p.PSE_BILLING_TYPE_C AS BILLING_TYPE,
      p.PROJECT_SKU_TYPE_C AS SKU_TYPE,
      p.INVESTMENT_TYPE_C AS INVESTMENT_TYPE,
      p.PSE_START_DATE_C AS START_DATE,
      p.PSE_END_DATE_C AS END_DATE,
      CAST(p.PSE_PLANNED_HOURS_C AS FLOAT) AS PLANNED_HOURS,
      CAST(p.PSE_BILLABLE_INTERNAL_HOURS_C AS FLOAT) AS BILLABLE_HOURS,
      CAST(p.PSE_PERCENT_HOURS_COMPLETE_C AS FLOAT) AS PCT_HOURS_COMPLETE,
      CAST(p.PROJECT_REVENUE_AMOUNT_C AS FLOAT) AS REVENUE_AMOUNT,
      p.ENGAGEMENT_MODEL_C AS ENGAGEMENT_MODEL,
      p.DELIVERY_MANAGER_ENGAGEMENT_C AS DELIVERY_MANAGER,
      p.SUB_AGREEMENT_TYPE_C AS AGREEMENT_TYPE,
      p.CHANNEL_TYPE_C AS CHANNEL_TYPE,
      p.PSE_PROJECT_STATUS_NOTES_C AS STATUS_NOTES,
      p.PRODUCT_TECHNOLOGY_STATUS_C AS PRODUCT_TECH_STATUS,
      p.PSE_OPPORTUNITY_C AS OPPORTUNITY_ID,
      c.NAME AS PROJECT_MANAGER,
      COALESCE(asn.ASSIGNMENT_COUNT, 0) AS ASSIGNMENT_COUNT,
      asn.RESOURCES AS ASSIGNED_RESOURCES,
      asn.ROLES AS ASSIGNED_ROLES,
      asn.LAST_RESOURCE_END_DATE,
      fo.PS_T_SELLER_C AS PS_SELLER_ID,
      ps_seller.NAME AS PS_SELLER_NAME,
      fo.PS_FORECAST_CATEGORY_C AS PS_FORECAST_CATEGORY,
      fo.PS_T_COMMENTS_C AS PS_COMMENTS,
      o.OPP_NAME AS OPPORTUNITY_NAME,
      o.STAGE_NAME AS OPP_STAGE,
      fc2.FISCAL_PERIOD AS FISCAL_QUARTER,
      o.REP_NAME AS OPP_OWNER,
      COALESCE(_dm.NAME, a.DM) AS DM,
      a.DISTRICT_NAME,
      a.REP_NAME AS AE
  FROM FIVETRAN.SALESFORCE.PSE_PROJ_C p
  JOIN SNOWHOUSE.SALES.ACCOUNTS_DAILY a ON p.PSE_ACCOUNT_C = a.ACCOUNT_ID AND a.DS = (SELECT MAX(DS) FROM SNOWHOUSE.SALES.ACCOUNTS_DAILY)
  LEFT JOIN (SELECT NAME, MANAGER_ID FROM FIVETRAN.SALESFORCE.USER WHERE IS_ACTIVE = true QUALIFY ROW_NUMBER() OVER (PARTITION BY NAME ORDER BY ID) = 1) _ae ON a.REP_NAME = _ae.NAME
  LEFT JOIN FIVETRAN.SALESFORCE.USER _dm ON _ae.MANAGER_ID = _dm.ID
  LEFT JOIN FIVETRAN.SALESFORCE.PSE_PRACTICE_C pr ON p.PSE_PRACTICE_C = pr.ID
  LEFT JOIN FIVETRAN.SALESFORCE.CONTACT c ON p.PSE_PROJECT_MANAGER_C = c.ID
  LEFT JOIN assignments asn ON p.ID = asn.PROJECT_ID
  LEFT JOIN FIVETRAN.SALESFORCE.OPPORTUNITY fo ON p.PSE_OPPORTUNITY_C = fo.ID
  LEFT JOIN FIVETRAN.SALESFORCE.USER ps_seller ON fo.PS_T_SELLER_C = ps_seller.ID
  LEFT JOIN SNOWHOUSE.SALES.OPPORTUNITIES_DAILY o ON p.PSE_OPPORTUNITY_C = o.OPP_ID AND o.DS = (SELECT MAX(DS) FROM SNOWHOUSE.SALES.OPPORTUNITIES_DAILY)
  LEFT JOIN SNOWHOUSE.UTILS.FISCAL_CALENDAR fc2 ON fc2._DATE = o.CLOSE_DATE
  WHERE a.ACCOUNT_STATUS = 'Active'
  AND p.IS_DELETED = FALSE
  AND p.PSE_IS_ACTIVE_C = TRUE
  AND p.PSE_STAGE_C IN ('In Progress', 'Stalled', 'Stalled - Expiring', 'Pipeline', 'Out Year')
  AND (p.PSE_END_DATE_C IS NULL OR p.PSE_END_DATE_C >= CURRENT_DATE())
  ORDER BY a.ACCOUNT_NAME, p.NAME;

  MERGE INTO SD_APPS_DB.SD_CENTER.SD_CACHE_METADATA t
  USING (SELECT 'SD_CACHE_PS_PROJECTS_ACTIVE' AS TABLE_NAME, CURRENT_TIMESTAMP() AS TS,
         (SELECT COUNT(*) FROM SD_APPS_DB.SD_CENTER.SD_CACHE_PS_PROJECTS_ACTIVE) AS CNT) s
  ON t.TABLE_NAME = s.TABLE_NAME
  WHEN MATCHED THEN UPDATE SET LAST_REFRESHED_AT = s.TS, ROW_COUNT = s.CNT
  WHEN NOT MATCHED THEN INSERT (TABLE_NAME, LAST_REFRESHED_AT, ROW_COUNT) VALUES (s.TABLE_NAME, s.TS, s.CNT);

  -- ── 6. SD_CACHE_PS_PIPELINE ───────────────────────────────────────────────
  CREATE OR REPLACE TABLE SD_APPS_DB.SD_CENTER.SD_CACHE_PS_PIPELINE AS
  WITH sda_opps AS (
      SELECT
          o.ACCOUNT_NAME,
          o.ACCOUNT_ID AS SALESFORCE_ACCOUNT_ID,
          o.OPP_NAME AS OPPORTUNITY_NAME,
          o.OPP_ID AS OPPORTUNITY_ID,
          o.TYPE AS OPPORTUNITY_TYPE,
          o.AGREEMENT_TYPE AS AGREEMENT_TYPE,
          o.STAGE_NAME,
          o.FORECAST_STATUS,
          CAST(COALESCE(fv.PRODUCT_ACV_LOOKER_C, fv.ACV_C, o.OPPORTUNITY_PRODUCT_ACV_TOTAL) AS FLOAT) AS TOTAL_ACV,
          o.CLOSE_DATE,
          fc.FISCAL_PERIOD AS FISCAL_QUARTER,
          NULL AS DAYS_IN_STAGE,
          o.REP_NAME AS OWNER,
          COALESCE(_dm.NAME, o.DM) AS DM,
          o.CREATED_DATE,
          CAST(o.PROBABILITY AS FLOAT) AS OPP_PROBABILITY,
          o.SALES_QUALIFIED_DATE,
          o.SE_COMMENTS_C AS SE_COMMENTS,
          o.NEXT_STEPS
      FROM SNOWHOUSE.SALES.OPPORTUNITIES_DAILY o
      LEFT JOIN SNOWHOUSE.UTILS.FISCAL_CALENDAR fc ON fc._DATE = o.CLOSE_DATE
      LEFT JOIN FIVETRAN.SALESFORCE.OPPORTUNITY fv ON fv.ID = o.OPP_ID
      LEFT JOIN (SELECT NAME, MANAGER_ID FROM FIVETRAN.SALESFORCE.USER WHERE IS_ACTIVE = true QUALIFY ROW_NUMBER() OVER (PARTITION BY NAME ORDER BY ID) = 1) _ae ON o.REP_NAME = _ae.NAME
      LEFT JOIN FIVETRAN.SALESFORCE.USER _dm ON _ae.MANAGER_ID = _dm.ID
      WHERE o.DS = (SELECT MAX(DS) FROM SNOWHOUSE.SALES.OPPORTUNITIES_DAILY)
      AND o.IS_CLOSED = FALSE
  ),
  fivetran_opps AS (
      SELECT
          a.ACCOUNT_NAME AS ACCOUNT_NAME,
          a.ACCOUNT_ID AS SALESFORCE_ACCOUNT_ID,
          opp.NAME AS OPPORTUNITY_NAME,
          opp.ID AS OPPORTUNITY_ID,
          opp.TYPE AS OPPORTUNITY_TYPE,
          opp.AGREEMENT_TYPE_C AS AGREEMENT_TYPE,
          opp.STAGE_NAME,
          opp.FORECAST_CATEGORY_NAME AS FORECAST_STATUS,
          CAST(opp.AMOUNT AS FLOAT) AS TOTAL_ACV,
          opp.CLOSE_DATE,
          fc2.FISCAL_PERIOD AS FISCAL_QUARTER,
          opp.LEAN_DATA_DAYS_IN_STAGE_C AS DAYS_IN_STAGE,
          u.NAME AS OWNER,
          COALESCE(_dm.NAME, a.DM) AS DM,
          opp.CREATED_DATE,
          CAST(opp.PROBABILITY AS FLOAT) AS OPP_PROBABILITY,
          NULL AS SALES_QUALIFIED_DATE,
          NULL AS SE_COMMENTS,
          opp.NEXT_STEP AS NEXT_STEPS
      FROM FIVETRAN.SALESFORCE.OPPORTUNITY opp
      JOIN SNOWHOUSE.SALES.ACCOUNTS_DAILY a ON opp.ACCOUNT_ID = a.ACCOUNT_ID AND a.DS = (SELECT MAX(DS) FROM SNOWHOUSE.SALES.ACCOUNTS_DAILY)
      LEFT JOIN (SELECT NAME, MANAGER_ID FROM FIVETRAN.SALESFORCE.USER WHERE IS_ACTIVE = true QUALIFY ROW_NUMBER() OVER (PARTITION BY NAME ORDER BY ID) = 1) _ae ON a.REP_NAME = _ae.NAME
      LEFT JOIN FIVETRAN.SALESFORCE.USER _dm ON _ae.MANAGER_ID = _dm.ID
      LEFT JOIN FIVETRAN.SALESFORCE.USER u ON opp.OWNER_ID = u.ID
      LEFT JOIN SNOWHOUSE.UTILS.FISCAL_CALENDAR fc2 ON fc2._DATE = opp.CLOSE_DATE
      LEFT JOIN (SELECT OPPORTUNITY_ID FROM sda_opps) sda_excl ON opp.ID = sda_excl.OPPORTUNITY_ID
      WHERE a.ACCOUNT_STATUS = 'Active'
      AND opp.IS_CLOSED = FALSE
      AND opp.IS_DELETED = FALSE
      AND sda_excl.OPPORTUNITY_ID IS NULL
  ),
  all_opps AS (
      SELECT * FROM sda_opps
      UNION ALL
      SELECT * FROM fivetran_opps
  ),
  ts_opps AS (
      SELECT DISTINCT oli.OPPORTUNITY_ID
      FROM FIVETRAN.SALESFORCE.OPPORTUNITY_LINE_ITEM oli
      WHERE oli.IS_DELETED = FALSE
      AND oli.PRODUCT_FAMILY_C IN ('Technical Services', 'Education Services')
  ),
  ts_filtered AS (
      SELECT ao.*
      FROM all_opps ao
      WHERE ao.OPPORTUNITY_ID IN (SELECT OPPORTUNITY_ID FROM ts_opps)
         OR ao.OPPORTUNITY_NAME ILIKE '%PS&T%'
         OR ao.OPPORTUNITY_NAME ILIKE '%PS_T%'
  ),
  products AS (
      SELECT
          oli.OPPORTUNITY_ID,
          LISTAGG(DISTINCT oli.OPPORTUNITY_PRODUCT_NAME_C, ', ') WITHIN GROUP (ORDER BY oli.OPPORTUNITY_PRODUCT_NAME_C) AS PRODUCT_NAMES
      FROM FIVETRAN.SALESFORCE.OPPORTUNITY_LINE_ITEM oli
      WHERE oli.IS_DELETED = FALSE
      AND oli.OPPORTUNITY_PRODUCT_NAME_C IS NOT NULL
      GROUP BY oli.OPPORTUNITY_ID
  )
  SELECT
      tf.ACCOUNT_NAME,
      tf.SALESFORCE_ACCOUNT_ID,
      tf.OPPORTUNITY_NAME,
      tf.OPPORTUNITY_ID,
      tf.OPPORTUNITY_TYPE,
      tf.STAGE_NAME,
      tf.FORECAST_STATUS,
      tf.TOTAL_ACV,
      tf.CLOSE_DATE,
      tf.FISCAL_QUARTER,
      tf.DAYS_IN_STAGE,
      tf.OWNER,
      tf.DM,
      tf.CREATED_DATE,
      tf.OPP_PROBABILITY,
      tf.SALES_QUALIFIED_DATE,
      tf.SE_COMMENTS,
      tf.NEXT_STEPS,
      fo.SERVICE_TYPE_C AS PS_SERVICE_TYPE,
      fo.PS_T_SELLER_C AS PS_SELLER_ID,
      ps_seller.NAME AS PS_SELLER_NAME,
      fo.PS_T_COMMENTS_C AS PS_COMMENTS,
      fo.INVESTMENT_TYPE_C AS PS_INVESTMENT_TYPE,
      CAST(fo.SERVICES_TCV_LOOKER_C AS FLOAT) AS PS_SERVICES_TCV,
      CAST(fo.EDUCATION_SERVICES_TCV_LOOKER_C AS FLOAT) AS EDUCATION_SERVICES_TCV,
      CAST(COALESCE(fo.SERVICES_TCV_LOOKER_C, 0) AS FLOAT) + CAST(COALESCE(fo.EDUCATION_SERVICES_TCV_LOOKER_C, 0) AS FLOAT) AS TOTAL_PST_TCV,
      CAST(fo.SERVICES_FORECAST_C AS FLOAT) AS PS_SERVICES_FORECAST,
      CAST(fo.EDUCATION_SERVICES_FORECAST_C AS FLOAT) AS EDUCATION_SERVICES_FORECAST,
      fo.PS_FORECAST_CATEGORY_C AS PS_FORECAST_CATEGORY,
      fo.SUB_AGREEMENT_TYPE_C AS QUOTE_SUB_AGREEMENT_TYPE,
      pr.PRODUCT_NAMES
  FROM ts_filtered tf
  LEFT JOIN FIVETRAN.SALESFORCE.OPPORTUNITY fo ON tf.OPPORTUNITY_ID = fo.ID
  LEFT JOIN FIVETRAN.SALESFORCE.USER ps_seller ON fo.PS_T_SELLER_C = ps_seller.ID
  LEFT JOIN products pr ON tf.OPPORTUNITY_ID = pr.OPPORTUNITY_ID
  ORDER BY tf.CLOSE_DATE ASC;

  MERGE INTO SD_APPS_DB.SD_CENTER.SD_CACHE_METADATA t
  USING (SELECT 'SD_CACHE_PS_PIPELINE' AS TABLE_NAME, CURRENT_TIMESTAMP() AS TS,
         (SELECT COUNT(*) FROM SD_APPS_DB.SD_CENTER.SD_CACHE_PS_PIPELINE) AS CNT) s
  ON t.TABLE_NAME = s.TABLE_NAME
  WHEN MATCHED THEN UPDATE SET LAST_REFRESHED_AT = s.TS, ROW_COUNT = s.CNT
  WHEN NOT MATCHED THEN INSERT (TABLE_NAME, LAST_REFRESHED_AT, ROW_COUNT) VALUES (s.TABLE_NAME, s.TS, s.CNT);

  -- ── 7. SD_CACHE_PS_HISTORY ────────────────────────────────────────────────
  CREATE OR REPLACE TABLE SD_APPS_DB.SD_CENTER.SD_CACHE_PS_HISTORY AS
  WITH opp_ps_summary AS (
      SELECT
          oli.OPPORTUNITY_ID,
          CAST(SUM(CASE WHEN oli.PRODUCT_FAMILY_C = 'Technical Services' THEN oli.TOTAL_PRICE ELSE 0 END) AS FLOAT) AS PS_SERVICES_ACV,
          CAST(SUM(CASE WHEN oli.PRODUCT_FAMILY_C = 'Education Services' THEN oli.TOTAL_PRICE ELSE 0 END) AS FLOAT) AS EDU_SERVICES_ACV,
          CAST(SUM(oli.TOTAL_PRICE) AS FLOAT) AS TOTAL_PST_AMOUNT,
          LISTAGG(DISTINCT oli.PRODUCT_FAMILY_C, ', ') WITHIN GROUP (ORDER BY oli.PRODUCT_FAMILY_C) AS PRODUCT_FAMILIES
      FROM FIVETRAN.SALESFORCE.OPPORTUNITY_LINE_ITEM oli
      WHERE oli.IS_DELETED = FALSE
      AND oli.PRODUCT_FAMILY_C IN ('Education Services', 'Technical Services')
      GROUP BY oli.OPPORTUNITY_ID
  )
  SELECT
      a.ACCOUNT_NAME AS ACCOUNT_NAME,
      opp.NAME AS OPPORTUNITY_NAME,
      opp.ID AS OPPORTUNITY_ID,
      COALESCE(_dm.NAME, a.DM) AS DM,
      a.DISTRICT_NAME,
      a.REP_NAME AS AE,
      u.NAME AS OPP_OWNER,
      opp.STAGE_NAME,
      opp.TYPE AS OPPORTUNITY_TYPE,
      opp.AGREEMENT_TYPE_C AS AGREEMENT_TYPE,
      opp.CLOSE_DATE,
      opp.SERVICE_TYPE_C AS PS_SERVICE_TYPE,
      opp.INVESTMENT_TYPE_C AS PS_INVESTMENT_TYPE,
      CAST(opp.PS_INVESTMENT_AMOUNT_C AS FLOAT) AS PS_INVESTMENT_AMOUNT,
      opp.PS_T_SELLER_C AS PS_SELLER_ID,
      ps_seller.NAME AS PS_SELLER_NAME,
      ops.PS_SERVICES_ACV,
      ops.EDU_SERVICES_ACV,
      ops.TOTAL_PST_AMOUNT,
      ops.PRODUCT_FAMILIES
  FROM FIVETRAN.SALESFORCE.OPPORTUNITY opp
  JOIN SNOWHOUSE.SALES.ACCOUNTS_DAILY a ON opp.ACCOUNT_ID = a.ACCOUNT_ID AND a.DS = (SELECT MAX(DS) FROM SNOWHOUSE.SALES.ACCOUNTS_DAILY)
  LEFT JOIN (SELECT NAME, MANAGER_ID FROM FIVETRAN.SALESFORCE.USER WHERE IS_ACTIVE = true QUALIFY ROW_NUMBER() OVER (PARTITION BY NAME ORDER BY ID) = 1) _ae ON a.REP_NAME = _ae.NAME
  LEFT JOIN FIVETRAN.SALESFORCE.USER _dm ON _ae.MANAGER_ID = _dm.ID
  JOIN opp_ps_summary ops ON opp.ID = ops.OPPORTUNITY_ID
  LEFT JOIN FIVETRAN.SALESFORCE.USER u ON opp.OWNER_ID = u.ID
  LEFT JOIN FIVETRAN.SALESFORCE.USER ps_seller ON opp.PS_T_SELLER_C = ps_seller.ID
  WHERE a.ACCOUNT_STATUS = 'Active'
  AND opp.IS_WON = TRUE
  AND opp.IS_DELETED = FALSE
  ORDER BY opp.CLOSE_DATE DESC;

  MERGE INTO SD_APPS_DB.SD_CENTER.SD_CACHE_METADATA t
  USING (SELECT 'SD_CACHE_PS_HISTORY' AS TABLE_NAME, CURRENT_TIMESTAMP() AS TS,
         (SELECT COUNT(*) FROM SD_APPS_DB.SD_CENTER.SD_CACHE_PS_HISTORY) AS CNT) s
  ON t.TABLE_NAME = s.TABLE_NAME
  WHEN MATCHED THEN UPDATE SET LAST_REFRESHED_AT = s.TS, ROW_COUNT = s.CNT
  WHEN NOT MATCHED THEN INSERT (TABLE_NAME, LAST_REFRESHED_AT, ROW_COUNT) VALUES (s.TABLE_NAME, s.TS, s.CNT);

  -- ── 8. SD_CACHE_ACTION_PLANNER ────────────────────────────────────────────
  CREATE OR REPLACE TABLE SD_APPS_DB.SD_CENTER.SD_CACHE_ACTION_PLANNER AS
  SELECT
      sa.ACCOUNT_NAME,
      sa.ACCOUNT_ID AS ACCOUNT_ID,
      COALESCE(_dm.NAME, sa.DM) AS DM,
      u.DISTRICT_C AS DISTRICT,
      sa.DISTRICT_NAME,
      sa.REP_NAME AS AE_NAME,
      lead_se.NAME AS SE_NAME,
      uc.ID AS USE_CASE_ID,
      uc.NAME_C AS USE_CASE_NAME,
      uc.STAGE_C AS STAGE,
      uc.USE_CASE_STATUS_C AS USE_CASE_STATUS,
      CAST(uc.ESTIMATED_ANNUAL_CREDIT_CONSUMPTION_C AS FLOAT) AS EACV,
      uc.TECHNICAL_USE_CASE_C AS TECHNICAL_UC,
      uc.COMPETITORS_C AS COMPETITORS,
      uc.IMPLEMENTER_C AS IMPLEMENTER,
      uc.USE_CASE_COMMENTS_C AS USE_CASE_COMMENTS,
      uc.NEXT_STEPS_C AS NEXT_STEPS,
      uc.NAME AS USE_CASE_NUMBER,
      uc.SPECIALIST_COMMENTS_C AS SE_COMMENTS_FULL
  FROM SNOWHOUSE.SALES.ACCOUNTS_DAILY sa
  JOIN FIVETRAN.SALESFORCE.ACCOUNT a ON sa.ACCOUNT_ID = a.ID
  JOIN FIVETRAN.SALESFORCE.USER u ON a.OWNER_ID = u.ID
  LEFT JOIN FIVETRAN.SALESFORCE.USER lead_se ON a.LEAD_SALES_ENGINEER_C = lead_se.ID
  JOIN FIVETRAN.SALESFORCE.USE_CASE_C uc ON uc.ACCOUNT_C = a.ID AND uc._FIVETRAN_DELETED = FALSE
  LEFT JOIN (SELECT NAME, MANAGER_ID FROM FIVETRAN.SALESFORCE.USER WHERE IS_ACTIVE = true QUALIFY ROW_NUMBER() OVER (PARTITION BY NAME ORDER BY ID) = 1) _ae ON sa.REP_NAME = _ae.NAME
  LEFT JOIN FIVETRAN.SALESFORCE.USER _dm ON _ae.MANAGER_ID = _dm.ID
  WHERE sa.DS = (SELECT MAX(DS) FROM SNOWHOUSE.SALES.ACCOUNTS_DAILY)
  AND sa.ACCOUNT_STATUS = 'Active'
  AND uc.STAGE_C IS NOT NULL
  AND uc.STAGE_C != '8 - Use Case Lost'
  ORDER BY sa.ACCOUNT_NAME, uc.ESTIMATED_ANNUAL_CREDIT_CONSUMPTION_C DESC NULLS LAST;

  MERGE INTO SD_APPS_DB.SD_CENTER.SD_CACHE_METADATA t
  USING (SELECT 'SD_CACHE_ACTION_PLANNER' AS TABLE_NAME, CURRENT_TIMESTAMP() AS TS,
         (SELECT COUNT(*) FROM SD_APPS_DB.SD_CENTER.SD_CACHE_ACTION_PLANNER) AS CNT) s
  ON t.TABLE_NAME = s.TABLE_NAME
  WHEN MATCHED THEN UPDATE SET LAST_REFRESHED_AT = s.TS, ROW_COUNT = s.CNT
  WHEN NOT MATCHED THEN INSERT (TABLE_NAME, LAST_REFRESHED_AT, ROW_COUNT) VALUES (s.TABLE_NAME, s.TS, s.CNT);

  -- ── 9. SD_CACHE_EXEC_SW_RENEWALS ──────────────────────────────────────────
  CREATE OR REPLACE TABLE SD_APPS_DB.SD_CENTER.SD_CACHE_EXEC_SW_RENEWALS AS
  SELECT
      o.NAME AS OPPORTUNITY_NAME,
      o.ID AS OPPORTUNITY_ID,
      a.ACCOUNT_NAME,
      a.ACCOUNT_ID AS SALESFORCE_ACCOUNT_ID,
      o.STAGE_NAME,
      o.FORECAST_CATEGORY_NAME AS FORECAST_STATUS,
      CAST(COALESCE(o.FORECAST_ACV_C, o.PRODUCT_ACV_LOOKER_C, o.ACV_C, o.AMOUNT) AS FLOAT) AS TOTAL_ACV,
      CAST(COALESCE(o.RENEWAL_ACV_LOOKER_C, o.ACV_C, 0) AS FLOAT) AS RENEWAL_ACV,
      CAST(o.PRODUCT_FORECAST_TCV_C AS FLOAT) AS PRODUCT_FORECAST_TCV,
      o.CLOSE_DATE,
      o.NEXT_STEPS_C AS NEXT_STEPS,
      a.REP_NAME AS OWNER,
      COALESCE(_dm.NAME, a.DM) AS DM,
      a.DISTRICT_NAME
  FROM FIVETRAN.SALESFORCE.OPPORTUNITY o
  JOIN SNOWHOUSE.SALES.ACCOUNTS_DAILY a ON o.ACCOUNT_ID = a.ACCOUNT_ID AND a.DS = (SELECT MAX(DS) FROM SNOWHOUSE.SALES.ACCOUNTS_DAILY)
  LEFT JOIN (SELECT NAME, MANAGER_ID FROM FIVETRAN.SALESFORCE.USER WHERE IS_ACTIVE = true QUALIFY ROW_NUMBER() OVER (PARTITION BY NAME ORDER BY ID) = 1) _ae ON a.REP_NAME = _ae.NAME
  LEFT JOIN FIVETRAN.SALESFORCE.USER _dm ON _ae.MANAGER_ID = _dm.ID
  WHERE o.IS_CLOSED = FALSE
  AND o.IS_DELETED = FALSE
  AND o.TYPE = 'Renewal'
  AND o.CLOSE_DATE BETWEEN CURRENT_DATE() AND DATEADD(MONTH, 8, CURRENT_DATE())
  ORDER BY o.CLOSE_DATE ASC;

  MERGE INTO SD_APPS_DB.SD_CENTER.SD_CACHE_METADATA t
  USING (SELECT 'SD_CACHE_EXEC_SW_RENEWALS' AS TABLE_NAME, CURRENT_TIMESTAMP() AS TS,
         (SELECT COUNT(*) FROM SD_APPS_DB.SD_CENTER.SD_CACHE_EXEC_SW_RENEWALS) AS CNT) s
  ON t.TABLE_NAME = s.TABLE_NAME
  WHEN MATCHED THEN UPDATE SET LAST_REFRESHED_AT = s.TS, ROW_COUNT = s.CNT
  WHEN NOT MATCHED THEN INSERT (TABLE_NAME, LAST_REFRESHED_AT, ROW_COUNT) VALUES (s.TABLE_NAME, s.TS, s.CNT);

  -- ── 10. SD_CACHE_EXEC_SVC_RENEWALS ────────────────────────────────────────
  --  (Replaces SALES.RAVEN.ACCOUNT reference with inline ACCOUNTS_DAILY join)
  CREATE OR REPLACE TABLE SD_APPS_DB.SD_CENTER.SD_CACHE_EXEC_SVC_RENEWALS AS
  WITH raven_accounts AS (
      SELECT
          a.ACCOUNT_ID AS SALESFORCE_ACCOUNT_ID,
          a.ACCOUNT_NAME AS NAME,
          a.REP_NAME AS ACCOUNT_OWNER_NAME,
          COALESCE(dm_user.NAME, a.DM) AS ACCOUNT_OWNER_MANAGER_C,
          a.ACCOUNT_STATUS AS ACCOUNT_STATUS_C,
          a.DISTRICT_NAME
      FROM SNOWHOUSE.SALES.ACCOUNTS_DAILY a
      LEFT JOIN (SELECT NAME, MANAGER_ID FROM FIVETRAN.SALESFORCE.USER WHERE IS_ACTIVE = true QUALIFY ROW_NUMBER() OVER (PARTITION BY NAME ORDER BY ID) = 1) ae_user ON a.REP_NAME = ae_user.NAME
      LEFT JOIN FIVETRAN.SALESFORCE.USER dm_user ON ae_user.MANAGER_ID = dm_user.ID
      WHERE a.DS = (SELECT MAX(DS) FROM SNOWHOUSE.SALES.ACCOUNTS_DAILY)
  )
  SELECT
      p.NAME AS PROJECT_NAME,
      p.ID AS PROJECT_ID,
      a.NAME AS ACCOUNT_NAME,
      a.SALESFORCE_ACCOUNT_ID,
      a.ACCOUNT_OWNER_MANAGER_C AS DM,
      a.ACCOUNT_OWNER_NAME AS AE,
      a.DISTRICT_NAME,
      p.SUB_AGREEMENT_TYPE_C AS AGREEMENT_TYPE,
      p.SERVICE_TYPE_C AS SERVICE_TYPE,
      p.PSE_STAGE_C AS PROJECT_STAGE,
      p.PSE_START_DATE_C AS START_DATE,
      p.PSE_END_DATE_C AS END_DATE,
      CAST(p.PROJECT_REVENUE_AMOUNT_C AS FLOAT) AS REVENUE_AMOUNT,
      p.DELIVERY_MANAGER_ENGAGEMENT_C AS DELIVERY_MANAGER,
      c.NAME AS PROJECT_MANAGER,
      p.PSE_OPPORTUNITY_C AS OPPORTUNITY_ID,
      DATEDIFF('day', CURRENT_DATE(), p.PSE_END_DATE_C) AS DAYS_TO_END
  FROM FIVETRAN.SALESFORCE.PSE_PROJ_C p
  JOIN raven_accounts a ON p.PSE_ACCOUNT_C = a.SALESFORCE_ACCOUNT_ID
  LEFT JOIN FIVETRAN.SALESFORCE.CONTACT c ON p.PSE_PROJECT_MANAGER_C = c.ID
  WHERE a.ACCOUNT_STATUS_C = 'Active'
  AND p.IS_DELETED = FALSE
  AND p.PSE_IS_ACTIVE_C = TRUE
  AND p.PSE_STAGE_C IN ('In Progress', 'Stalled', 'Stalled - Expiring', 'Pipeline', 'Out Year')
  AND p.PSE_END_DATE_C BETWEEN CURRENT_DATE() AND DATEADD(MONTH, 6, CURRENT_DATE())
  ORDER BY p.PSE_END_DATE_C ASC;

  MERGE INTO SD_APPS_DB.SD_CENTER.SD_CACHE_METADATA t
  USING (SELECT 'SD_CACHE_EXEC_SVC_RENEWALS' AS TABLE_NAME, CURRENT_TIMESTAMP() AS TS,
         (SELECT COUNT(*) FROM SD_APPS_DB.SD_CENTER.SD_CACHE_EXEC_SVC_RENEWALS) AS CNT) s
  ON t.TABLE_NAME = s.TABLE_NAME
  WHEN MATCHED THEN UPDATE SET LAST_REFRESHED_AT = s.TS, ROW_COUNT = s.CNT
  WHEN NOT MATCHED THEN INSERT (TABLE_NAME, LAST_REFRESHED_AT, ROW_COUNT) VALUES (s.TABLE_NAME, s.TS, s.CNT);

  -- ── 11. SD_CACHE_EXEC_NEW_OPPS ────────────────────────────────────────────
  --  (Replaces SALES.RAVEN.ACCOUNT in fivetran_new branch)
  CREATE OR REPLACE TABLE SD_APPS_DB.SD_CENTER.SD_CACHE_EXEC_NEW_OPPS AS
  WITH raven_accounts AS (
      SELECT
          a.ACCOUNT_ID AS SALESFORCE_ACCOUNT_ID,
          a.ACCOUNT_NAME AS NAME,
          COALESCE(dm_user.NAME, a.DM) AS ACCOUNT_OWNER_MANAGER_C,
          a.ACCOUNT_STATUS AS ACCOUNT_STATUS_C,
          a.DISTRICT_NAME
      FROM SNOWHOUSE.SALES.ACCOUNTS_DAILY a
      LEFT JOIN (SELECT NAME, MANAGER_ID FROM FIVETRAN.SALESFORCE.USER WHERE IS_ACTIVE = true QUALIFY ROW_NUMBER() OVER (PARTITION BY NAME ORDER BY ID) = 1) ae_user ON a.REP_NAME = ae_user.NAME
      LEFT JOIN FIVETRAN.SALESFORCE.USER dm_user ON ae_user.MANAGER_ID = dm_user.ID
      WHERE a.DS = (SELECT MAX(DS) FROM SNOWHOUSE.SALES.ACCOUNTS_DAILY)
  ),
  sda_new AS (
      SELECT
          o.ACCOUNT_NAME,
          o.ACCOUNT_ID AS SALESFORCE_ACCOUNT_ID,
          o.OPP_NAME AS OPPORTUNITY_NAME,
          o.OPP_ID AS OPPORTUNITY_ID,
          o.TYPE AS OPPORTUNITY_TYPE,
          o.AGREEMENT_TYPE AS AGREEMENT_TYPE,
          o.STAGE_NAME,
          o.FORECAST_STATUS,
          CAST(COALESCE(fv.PRODUCT_ACV_LOOKER_C, fv.ACV_C, o.OPPORTUNITY_PRODUCT_ACV_TOTAL) AS FLOAT) AS TOTAL_ACV,
          o.CLOSE_DATE,
          o.CREATED_DATE,
          o.REP_NAME AS OWNER,
          COALESCE(_dm.NAME, o.DM) AS DM
      FROM SNOWHOUSE.SALES.OPPORTUNITIES_DAILY o
      LEFT JOIN FIVETRAN.SALESFORCE.OPPORTUNITY fv ON fv.ID = o.OPP_ID
      LEFT JOIN (SELECT NAME, MANAGER_ID FROM FIVETRAN.SALESFORCE.USER WHERE IS_ACTIVE = true QUALIFY ROW_NUMBER() OVER (PARTITION BY NAME ORDER BY ID) = 1) _ae ON o.REP_NAME = _ae.NAME
      LEFT JOIN FIVETRAN.SALESFORCE.USER _dm ON _ae.MANAGER_ID = _dm.ID
      WHERE o.DS = (SELECT MAX(DS) FROM SNOWHOUSE.SALES.OPPORTUNITIES_DAILY)
      AND o.CREATED_DATE >= DATEADD('day', -90, CURRENT_DATE())
  ),
  fivetran_new AS (
      SELECT
          a.NAME AS ACCOUNT_NAME,
          a.SALESFORCE_ACCOUNT_ID,
          opp.NAME AS OPPORTUNITY_NAME,
          opp.ID AS OPPORTUNITY_ID,
          opp.TYPE AS OPPORTUNITY_TYPE,
          opp.AGREEMENT_TYPE_C AS AGREEMENT_TYPE,
          opp.STAGE_NAME,
          opp.FORECAST_CATEGORY_NAME AS FORECAST_STATUS,
          CAST(opp.AMOUNT AS FLOAT) AS TOTAL_ACV,
          opp.CLOSE_DATE,
          opp.CREATED_DATE,
          u.NAME AS OWNER,
          a.ACCOUNT_OWNER_MANAGER_C AS DM
      FROM FIVETRAN.SALESFORCE.OPPORTUNITY opp
      JOIN raven_accounts a ON opp.ACCOUNT_ID = a.SALESFORCE_ACCOUNT_ID
      LEFT JOIN FIVETRAN.SALESFORCE.USER u ON opp.OWNER_ID = u.ID
      WHERE a.ACCOUNT_STATUS_C = 'Active'
      AND opp.IS_DELETED = FALSE
      AND opp.CREATED_DATE >= DATEADD('day', -90, CURRENT_DATE())
      AND opp.ID NOT IN (SELECT OPPORTUNITY_ID FROM sda_new)
  )
  SELECT * FROM sda_new
  UNION ALL
  SELECT * FROM fivetran_new
  ORDER BY CREATED_DATE DESC;

  MERGE INTO SD_APPS_DB.SD_CENTER.SD_CACHE_METADATA t
  USING (SELECT 'SD_CACHE_EXEC_NEW_OPPS' AS TABLE_NAME, CURRENT_TIMESTAMP() AS TS,
         (SELECT COUNT(*) FROM SD_APPS_DB.SD_CENTER.SD_CACHE_EXEC_NEW_OPPS) AS CNT) s
  ON t.TABLE_NAME = s.TABLE_NAME
  WHEN MATCHED THEN UPDATE SET LAST_REFRESHED_AT = s.TS, ROW_COUNT = s.CNT
  WHEN NOT MATCHED THEN INSERT (TABLE_NAME, LAST_REFRESHED_AT, ROW_COUNT) VALUES (s.TABLE_NAME, s.TS, s.CNT);

  -- ── 12. SD_CACHE_EXEC_NEW_UCS ─────────────────────────────────────────────
  CREATE OR REPLACE TABLE SD_APPS_DB.SD_CENTER.SD_CACHE_EXEC_NEW_UCS AS
  SELECT
      a.ACCOUNT_NAME,
      a.ACCOUNT_ID AS SALESFORCE_ACCOUNT_ID,
      uc.NAME_C AS USE_CASE_NAME,
      uc.USE_CASE_STATUS_C AS USE_CASE_STATUS,
      CAST(uc.ESTIMATED_ANNUAL_CREDIT_CONSUMPTION_C AS FLOAT) AS ACV,
      uc.STAGE_C AS STAGE,
      uc.CREATED_DATE,
      u.NAME AS OWNER,
      uc.NEXT_STEPS_C AS NEXT_STEPS,
      COALESCE(_dm.NAME, a.DM) AS DM,
      a.DISTRICT_NAME,
      uc.ID AS USE_CASE_ID,
      uc.NAME AS USE_CASE_NUMBER
  FROM FIVETRAN.SALESFORCE.USE_CASE_C uc
  JOIN SNOWHOUSE.SALES.ACCOUNTS_DAILY a ON uc.ACCOUNT_C = a.ACCOUNT_ID AND a.DS = (SELECT MAX(DS) FROM SNOWHOUSE.SALES.ACCOUNTS_DAILY)
  LEFT JOIN (SELECT NAME, MANAGER_ID FROM FIVETRAN.SALESFORCE.USER WHERE IS_ACTIVE = true QUALIFY ROW_NUMBER() OVER (PARTITION BY NAME ORDER BY ID) = 1) _ae ON a.REP_NAME = _ae.NAME
  LEFT JOIN FIVETRAN.SALESFORCE.USER _dm ON _ae.MANAGER_ID = _dm.ID
  LEFT JOIN FIVETRAN.SALESFORCE.USER u ON uc.OWNER_ID = u.ID
  WHERE uc.STAGE_C IS NOT NULL
  AND uc.STAGE_C != '8 - Use Case Lost'
  AND uc._FIVETRAN_DELETED = FALSE
  AND uc.CREATED_DATE >= DATEADD('day', -90, CURRENT_DATE())
  ORDER BY uc.CREATED_DATE DESC;

  MERGE INTO SD_APPS_DB.SD_CENTER.SD_CACHE_METADATA t
  USING (SELECT 'SD_CACHE_EXEC_NEW_UCS' AS TABLE_NAME, CURRENT_TIMESTAMP() AS TS,
         (SELECT COUNT(*) FROM SD_APPS_DB.SD_CENTER.SD_CACHE_EXEC_NEW_UCS) AS CNT) s
  ON t.TABLE_NAME = s.TABLE_NAME
  WHEN MATCHED THEN UPDATE SET LAST_REFRESHED_AT = s.TS, ROW_COUNT = s.CNT
  WHEN NOT MATCHED THEN INSERT (TABLE_NAME, LAST_REFRESHED_AT, ROW_COUNT) VALUES (s.TABLE_NAME, s.TS, s.CNT);

  -- ── 13. SD_CACHE_MILESTONE_ACV ────────────────────────────────────────────
  CREATE OR REPLACE TABLE SD_APPS_DB.SD_CENTER.SD_CACHE_MILESTONE_ACV AS
  SELECT
      m.SALESFORCE_PROFESSIONAL_SERVICES_MILESTONE_NAME AS MILESTONE_NAME,
      m.SALESFORCE_PROFESSIONAL_SERVICES_MILESTONE_STATUS AS MILESTONE_STATUS,
      m.SALESFORCE_PROFESSIONAL_SERVICES_MILESTONE_ID AS MILESTONE_ID,
      m.SALESFORCE_PROFESSIONAL_SERVICES_PROJECT_NAME AS PROJECT_NAME,
      m.SALESFORCE_PROFESSIONAL_SERVICES_PROJECT_STAGE AS PROJECT_STAGE,
      m.SALESFORCE_PROFESSIONAL_SERVICES_PROJECT_STATUS AS PROJECT_STATUS,
      m.SALESFORCE_PROFESSIONAL_SERVICES_PROJECT_START_DATE AS PROJECT_START,
      m.SALESFORCE_PROFESSIONAL_SERVICES_PROJECT_END_DATE AS PROJECT_END,
      m.SALESFORCE_ACCOUNT_NAME AS ACCOUNT_NAME,
      m.SALESFORCE_ACCOUNT_ID,
      m.SALESFORCE_TERRITORY_DISTRICT AS DISTRICT,
      m.SALESFORCE_ACCOUNT_EXECUTIVE AS AE,
      uc.SALESFORCE_USE_CASE_STAGE AS USE_CASE_STAGE,
      uc.SALESFORCE_USE_CASE_GO_LIVE_DATE AS GO_LIVE_DATE,
      CAST(uc.SALESFORCE_USE_CASE_ESTIMATED_ANNUAL_CREDIT_CONSUMPTION AS FLOAT) AS ESTIMATED_ACV,
      fc.FISCAL_QUARTER_FYYYYY_QQ AS FISCAL_QUARTER_LABEL
  FROM SNOW_CERTIFIED.PROFESSIONAL_SERVICES.DD_PROFESSIONAL_SERVICES_MILESTONE m
  LEFT JOIN SNOW_CERTIFIED.SALESFORCE_USE_CASE.DD_SALESFORCE_USE_CASE uc
      ON m.SALESFORCE_USE_CASE_ID = uc.SALESFORCE_USE_CASE_ID
  LEFT JOIN SNOWHOUSE.UTILS.FISCAL_CALENDAR fc
      ON fc._DATE = uc.SALESFORCE_USE_CASE_GO_LIVE_DATE
  WHERE m.SALESFORCE_PROFESSIONAL_SERVICES_MILESTONE_TYPE = 'Use Case'
  AND uc.SALESFORCE_USE_CASE_GO_LIVE_DATE IS NOT NULL
  ORDER BY uc.SALESFORCE_USE_CASE_GO_LIVE_DATE;

  MERGE INTO SD_APPS_DB.SD_CENTER.SD_CACHE_METADATA t
  USING (SELECT 'SD_CACHE_MILESTONE_ACV' AS TABLE_NAME, CURRENT_TIMESTAMP() AS TS,
         (SELECT COUNT(*) FROM SD_APPS_DB.SD_CENTER.SD_CACHE_MILESTONE_ACV) AS CNT) s
  ON t.TABLE_NAME = s.TABLE_NAME
  WHEN MATCHED THEN UPDATE SET LAST_REFRESHED_AT = s.TS, ROW_COUNT = s.CNT
  WHEN NOT MATCHED THEN INSERT (TABLE_NAME, LAST_REFRESHED_AT, ROW_COUNT) VALUES (s.TABLE_NAME, s.TS, s.CNT);

  -- ── 14. SD_CACHE_WOW_USE_CASES ────────────────────────────────────────────
  --  Stores 14 days; Python filters by requested window
  CREATE OR REPLACE TABLE SD_APPS_DB.SD_CENTER.SD_CACHE_WOW_USE_CASES AS
  SELECT
      a.ACCOUNT_NAME,
      a.REP_NAME AS AE,
      uc.NAME_C AS USE_CASE_NAME,
      uc.ID AS USE_CASE_ID,
      uc.NAME AS USE_CASE_NUMBER,
      uc.STAGE_C AS CURRENT_STAGE,
      CAST(uc.ESTIMATED_ANNUAL_CREDIT_CONSUMPTION_C AS FLOAT) AS ACV,
      uc.DECISION_DATE_C AS DECISION_DATE,
      uc.TECHNICAL_WIN_DATE_FORECAST_C AS TARGET_GO_LIVE,
      uc.USE_CASE_STATUS_C AS UC_STATUS,
      h.FIELD,
      h.OLD_VALUE,
      h.NEW_VALUE,
      h.CREATED_DATE AS CHANGED_AT,
      COALESCE(_dm.NAME, a.DM) AS DM,
      a.DISTRICT_NAME
  FROM FIVETRAN.SALESFORCE.USE_CASE_HISTORY h
  JOIN FIVETRAN.SALESFORCE.USE_CASE_C uc ON h.PARENT_ID = uc.ID
  JOIN SNOWHOUSE.SALES.ACCOUNTS_DAILY a ON uc.ACCOUNT_C = a.ACCOUNT_ID AND a.DS = (SELECT MAX(DS) FROM SNOWHOUSE.SALES.ACCOUNTS_DAILY)
  LEFT JOIN (SELECT NAME, MANAGER_ID FROM FIVETRAN.SALESFORCE.USER WHERE IS_ACTIVE = true QUALIFY ROW_NUMBER() OVER (PARTITION BY NAME ORDER BY ID) = 1) _ae ON a.REP_NAME = _ae.NAME
  LEFT JOIN FIVETRAN.SALESFORCE.USER _dm ON _ae.MANAGER_ID = _dm.ID
  WHERE h.FIELD IN ('Stage__c', 'Technical_Win__c', 'Actual_Go_Live_Date__c')
  AND h.CREATED_DATE >= DATEADD('day', -14, CURRENT_DATE())
  AND h._FIVETRAN_DELETED = FALSE
  ORDER BY h.CREATED_DATE DESC;

  MERGE INTO SD_APPS_DB.SD_CENTER.SD_CACHE_METADATA t
  USING (SELECT 'SD_CACHE_WOW_USE_CASES' AS TABLE_NAME, CURRENT_TIMESTAMP() AS TS,
         (SELECT COUNT(*) FROM SD_APPS_DB.SD_CENTER.SD_CACHE_WOW_USE_CASES) AS CNT) s
  ON t.TABLE_NAME = s.TABLE_NAME
  WHEN MATCHED THEN UPDATE SET LAST_REFRESHED_AT = s.TS, ROW_COUNT = s.CNT
  WHEN NOT MATCHED THEN INSERT (TABLE_NAME, LAST_REFRESHED_AT, ROW_COUNT) VALUES (s.TABLE_NAME, s.TS, s.CNT);

  -- ── 15. SD_CACHE_WOW_PROJECTS ─────────────────────────────────────────────
  --  Stores 14 days; Python filters by requested window
  CREATE OR REPLACE TABLE SD_APPS_DB.SD_CENTER.SD_CACHE_WOW_PROJECTS AS
  SELECT
      a.ACCOUNT_NAME,
      a.REP_NAME AS AE,
      p.NAME AS PROJECT_NAME,
      p.ID AS PROJECT_ID,
      p.PSE_STAGE_C AS CURRENT_STAGE,
      p.PSE_PROJECT_STATUS_C AS PROJECT_STATUS,
      p.PSE_BILLING_TYPE_C AS BILLING_TYPE,
      p.SERVICE_TYPE_C AS SERVICE_TYPE,
      p.PSE_START_DATE_C AS START_DATE,
      p.PSE_END_DATE_C AS END_DATE,
      CAST(p.PROJECT_REVENUE_AMOUNT_C AS FLOAT) AS REVENUE_AMOUNT,
      CAST(p.PSE_PERCENT_HOURS_COMPLETE_C AS FLOAT) AS PCT_COMPLETE,
      h.FIELD,
      h.OLD_VALUE,
      h.NEW_VALUE,
      h.CREATED_DATE AS CHANGED_AT,
      COALESCE(_dm.NAME, a.DM) AS DM,
      a.DISTRICT_NAME
  FROM FIVETRAN.SALESFORCE.PSE_PROJ_HISTORY h
  JOIN FIVETRAN.SALESFORCE.PSE_PROJ_C p ON h.PARENT_ID = p.ID
  JOIN SNOWHOUSE.SALES.ACCOUNTS_DAILY a ON p.PSE_ACCOUNT_C = a.ACCOUNT_ID AND a.DS = (SELECT MAX(DS) FROM SNOWHOUSE.SALES.ACCOUNTS_DAILY)
  LEFT JOIN (SELECT NAME, MANAGER_ID FROM FIVETRAN.SALESFORCE.USER WHERE IS_ACTIVE = true QUALIFY ROW_NUMBER() OVER (PARTITION BY NAME ORDER BY ID) = 1) _ae ON a.REP_NAME = _ae.NAME
  LEFT JOIN FIVETRAN.SALESFORCE.USER _dm ON _ae.MANAGER_ID = _dm.ID
  WHERE h.FIELD IN ('pse__Stage__c', 'pse__Project_Status__c')
  AND h.CREATED_DATE >= DATEADD('day', -14, CURRENT_DATE())
  AND h._FIVETRAN_DELETED = FALSE
  ORDER BY h.CREATED_DATE DESC;

  MERGE INTO SD_APPS_DB.SD_CENTER.SD_CACHE_METADATA t
  USING (SELECT 'SD_CACHE_WOW_PROJECTS' AS TABLE_NAME, CURRENT_TIMESTAMP() AS TS,
         (SELECT COUNT(*) FROM SD_APPS_DB.SD_CENTER.SD_CACHE_WOW_PROJECTS) AS CNT) s
  ON t.TABLE_NAME = s.TABLE_NAME
  WHEN MATCHED THEN UPDATE SET LAST_REFRESHED_AT = s.TS, ROW_COUNT = s.CNT
  WHEN NOT MATCHED THEN INSERT (TABLE_NAME, LAST_REFRESHED_AT, ROW_COUNT) VALUES (s.TABLE_NAME, s.TS, s.CNT);

  RETURN 'Refresh complete: ' || CURRENT_TIMESTAMP()::VARCHAR;
END;
$$;

-- ---------------------------------------------------------------------------
-- 3. Scheduled Task: runs twice daily at 7am and 7pm Pacific (14:00 / 02:00 UTC)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TASK SD_APPS_DB.SD_CENTER.SD_CACHE_REFRESH_TASK
    WAREHOUSE    = PST_STEAMLIT_APPS
    SCHEDULE     = 'USING CRON 0 14,2 * * * UTC'
    COMMENT      = 'Refreshes SD Presales Dashboard cache tables twice daily'
AS
    CALL SD_APPS_DB.SD_CENTER.REFRESH_CACHE_ALL();

ALTER TASK SD_APPS_DB.SD_CENTER.SD_CACHE_REFRESH_TASK RESUME;

-- ---------------------------------------------------------------------------
-- 4. Initial population: run once to populate all tables immediately
-- ---------------------------------------------------------------------------
CALL SD_APPS_DB.SD_CENTER.REFRESH_CACHE_ALL();

-- Verify: check that all 15 tables are populated with recent timestamps
SELECT TABLE_NAME, LAST_REFRESHED_AT, ROW_COUNT
FROM SD_APPS_DB.SD_CENTER.SD_CACHE_METADATA
ORDER BY TABLE_NAME;
