-- Weekly Snapshot Tasks for PS Dashboard trend tracking
-- Requires: CREATE TASK on PST.PS_APPS_DEV (PST_ADMIN_RL or SALES_ENGINEER)
-- Run once to create, then: ALTER TASK ... RESUME to activate
--
-- Request: GRANT CREATE TASK ON SCHEMA PST.PS_APPS_DEV TO ROLE TECHNICAL_ACCOUNT_MANAGER;

-- Task 1: Dashboard KPI snapshot (Sundays 6am CT)
CREATE OR REPLACE TASK PST.PS_APPS_DEV.SNAPSHOT_DASHBOARD_KPIS
  WAREHOUSE = PST_STEAMLIT_APPS
  SCHEDULE = 'USING CRON 0 6 * * 0 America/Chicago'
  COMMENT = 'Weekly dashboard KPI snapshot for WoW/MoM deltas'
AS
INSERT INTO PST.PS_APPS_DEV.PS_DASHBOARD_SNAPSHOTS
    (SNAPSHOT_DATE, DISTRICT, PS_ENGAGED_COUNT, PS_ENGAGED_EACV, GOLIVE_COUNT,
     AT_RISK_COUNT, IMPL_COUNT, ADVISORY_COUNT, PROPOSING_COUNT, SUPPORT_COUNT,
     SF_PS_LED_COUNT, TOTAL_PROJECTS)
WITH ps AS (
    SELECT * FROM PST.PS_APPS_DEV.SDA_USE_CASES_CACHE
    WHERE PS_ENGAGEMENT IN ('Implementation','Advisory','Proposing','Support')
       OR IS_PS_ENGAGED = TRUE
)
SELECT
    CURRENT_DATE(), DISTRICT, COUNT(*), COALESCE(SUM(USE_CASE_ACV), 0),
    0, 0,
    SUM(CASE WHEN PS_ENGAGEMENT = 'Implementation' THEN 1 ELSE 0 END),
    SUM(CASE WHEN PS_ENGAGEMENT = 'Advisory' THEN 1 ELSE 0 END),
    SUM(CASE WHEN PS_ENGAGEMENT = 'Proposing' THEN 1 ELSE 0 END),
    SUM(CASE WHEN PS_ENGAGEMENT = 'Support' THEN 1 ELSE 0 END),
    SUM(CASE WHEN IMPLEMENTER IN ('Snowflake SD Prime','Partner Prime + Snowflake SD',
        'Customer Prime + Snowflake SD') THEN 1 ELSE 0 END),
    0
FROM ps GROUP BY DISTRICT;

ALTER TASK PST.PS_APPS_DEV.SNAPSHOT_DASHBOARD_KPIS RESUME;


-- Task 2: Project health snapshot (Sundays 6am CT)
CREATE OR REPLACE TASK PST.PS_APPS_DEV.SNAPSHOT_PROJECT_HEALTH
  WAREHOUSE = PST_STEAMLIT_APPS
  SCHEDULE = 'USING CRON 0 6 * * 0 America/Chicago'
  COMMENT = 'Weekly project health snapshot for sparklines'
AS
INSERT INTO PST.PS_APPS_DEV.PROJECT_HEALTH_SNAPSHOTS
    (SNAPSHOT_DATE, PROJECT_ID, ACCOUNT_NAME, PROJECT_NAME,
     PROJECT_STATUS, SCOPE_HEALTH, SCHEDULE_HEALTH, CONSUMPTION_HEALTH,
     HEALTH_SCORE, HRS_REM)
SELECT
    CURRENT_DATE(), PROJECT_ID, ACCOUNT_NAME, PROJECT_NAME,
    PROJECT_STATUS, SCOPE_HEALTH, SCHEDULE_HEALTH, CONSUMPTION_HEALTH,
    (CASE PROJECT_STATUS WHEN 'Green' THEN 3 WHEN 'Yellow' THEN 2 WHEN 'Red' THEN 1 ELSE 0 END
   + CASE SCOPE_HEALTH WHEN 'Green' THEN 3 WHEN 'Yellow' THEN 2 WHEN 'Red' THEN 1 ELSE 0 END
   + CASE SCHEDULE_HEALTH WHEN 'Green' THEN 3 WHEN 'Yellow' THEN 2 WHEN 'Red' THEN 1 ELSE 0 END
   + CASE CONSUMPTION_HEALTH WHEN 'Green' THEN 3 WHEN 'Yellow' THEN 2 WHEN 'Red' THEN 1 ELSE 0 END
    ) / 4.0,
    TRY_TO_DOUBLE(REMAINING_HOURS)
FROM SMARTSHEET_DB.RAW_SMARTSHEET.SHEET_1030823650217860_SFDC_CONNECTOR_SHEET_PROJECTS
WHERE ACTIVE = 'true';

ALTER TASK PST.PS_APPS_DEV.SNAPSHOT_PROJECT_HEALTH RESUME;
